import { lazy, type ComponentType } from 'react'
import type { IconName } from '../components/Icon'

export type GameCategory =
  | 'Puzzle'
  | 'Reflex'
  | 'Memory'
  | 'Arcade'
  | 'Word'
  | 'Strategy'

export type GameMeta = {
  id: string
  title: string
  tagline: string
  category: GameCategory
  /** Icon from the inline SVG set. */
  icon: IconName
  /** Two colors for the card's gradient. */
  colors: [string, string]
  /** How the best score should be read. */
  scoring: 'high' | 'low' | 'none'
  scoreLabel: string
  howTo: string[]
  Component: ComponentType
}

/** Each game is code-split so the first paint stays small. */
export const GAMES: GameMeta[] = [
  {
    id: 'memory',
    title: 'Memory Match',
    tagline: 'Pair the glyphs before your moves run out',
    category: 'Memory',
    icon: 'brain',
    colors: ['#8b5cf6', '#d946ef'],
    scoring: 'low',
    scoreLabel: 'Fewest moves',
    howTo: [
      'Tap a card to reveal the glyph beneath it.',
      'Find its twin — matched pairs stay face up.',
      'Clear the board in as few moves as you can.',
    ],
    Component: lazy(() => import('./memory/MemoryMatch')),
  },
  {
    id: 'twenty48',
    title: '2048',
    tagline: 'Slide, merge and chase the big tile',
    category: 'Puzzle',
    icon: 'grid',
    colors: ['#f59e0b', '#ef4444'],
    scoring: 'high',
    scoreLabel: 'Top score',
    howTo: [
      'Swipe (or use arrow keys) to slide every tile at once.',
      'Equal tiles merge into their double.',
      'The board fills as you go — plan your moves.',
    ],
    Component: lazy(() => import('./twenty48/Twenty48')),
  },
  {
    id: 'reaction',
    title: 'Reaction',
    tagline: 'How fast are your reflexes, really?',
    category: 'Reflex',
    icon: 'bolt',
    colors: ['#22d3ee', '#3b82f6'],
    scoring: 'low',
    scoreLabel: 'Best average',
    howTo: [
      'Wait for the pad to turn green.',
      'Tap the instant it does — tapping early resets the round.',
      'Five rounds make up your average.',
    ],
    Component: lazy(() => import('./reaction/Reaction')),
  },
  {
    id: 'snake',
    title: 'Snake',
    tagline: 'Grow long, never bite yourself',
    category: 'Arcade',
    icon: 'snake',
    colors: ['#a3e635', '#10b981'],
    scoring: 'high',
    scoreLabel: 'Longest run',
    howTo: [
      'Swipe or use the arrow keys to steer.',
      'Eat the orbs to grow and score.',
      'Walls and your own tail end the run.',
    ],
    Component: lazy(() => import('./snake/Snake')),
  },
  {
    id: 'whack',
    title: 'Whack-a-Mole',
    tagline: 'Thirty seconds, endless targets',
    category: 'Reflex',
    icon: 'crosshair',
    colors: ['#fb7185', '#f43f5e'],
    scoring: 'high',
    scoreLabel: 'Most hits',
    howTo: [
      'Tap the glowing targets as they appear.',
      'Chains of quick hits multiply your score.',
      'Bombs cost you — leave them alone.',
    ],
    Component: lazy(() => import('./whack/TapRush')),
  },
  {
    id: 'simon',
    title: 'Simon',
    tagline: 'Repeat the pattern, one step longer each time',
    category: 'Memory',
    icon: 'waveform',
    colors: ['#6366f1', '#8b5cf6'],
    scoring: 'high',
    scoreLabel: 'Longest sequence',
    howTo: [
      'Watch the pads light up in order.',
      'Tap them back in the same order.',
      'Each round adds one more step.',
    ],
    Component: lazy(() => import('./simon/Echo')),
  },
  {
    id: 'minesweeper',
    title: 'Minesweeper',
    tagline: 'Read the numbers, flag the danger',
    category: 'Puzzle',
    icon: 'gem',
    colors: ['#14b8a6', '#0ea5e9'],
    scoring: 'low',
    scoreLabel: 'Fastest clear',
    howTo: [
      'Tap to reveal a tile; numbers count adjacent mines.',
      'Long-press (or right-click) to flag a suspect.',
      'Clear every safe tile to win.',
    ],
    Component: lazy(() => import('./minesweeper/Minefield')),
  },
  {
    id: 'wordle',
    title: 'Wordle',
    tagline: 'Six guesses to crack the five-letter word',
    category: 'Word',
    icon: 'letters',
    colors: ['#84cc16', '#22c55e'],
    scoring: 'low',
    scoreLabel: 'Fewest guesses',
    howTo: [
      'Guess any five-letter word to start.',
      'Green means right letter, right spot; amber means wrong spot.',
      'You get six tries.',
    ],
    Component: lazy(() => import('./wordle/WordHunt')),
  },
  {
    id: 'tetris',
    title: 'Tetris',
    tagline: 'Stack the falling pieces, clear the lines',
    category: 'Arcade',
    icon: 'blocks',
    colors: ['#06b6d4', '#6366f1'],
    scoring: 'high',
    scoreLabel: 'Top score',
    howTo: [
      'Swipe left and right to move the falling piece, or use the arrow keys.',
      'Tap the piece (or press up) to rotate it; swipe down to drop it fast.',
      'Fill a whole row to clear it — four at once scores the most.',
    ],
    Component: lazy(() => import('./tetris/BlockDrop')),
  },
  {
    id: 'flappy',
    title: 'Flappy Bird',
    tagline: 'One tap keeps you airborne',
    category: 'Reflex',
    icon: 'wing',
    colors: ['#facc15', '#fb923c'],
    scoring: 'high',
    scoreLabel: 'Most pipes',
    howTo: [
      'Tap anywhere (or press space) to flap upward.',
      'Gravity pulls you down the moment you stop.',
      'Thread the gaps — touching a pipe or the ground ends the run.',
    ],
    Component: lazy(() => import('./flappy/SkyHop')),
  },
  {
    id: 'sudoku',
    title: 'Sudoku',
    tagline: 'Nine by nine, one of each',
    category: 'Puzzle',
    icon: 'sudoku',
    colors: ['#0ea5e9', '#8b5cf6'],
    scoring: 'low',
    scoreLabel: 'Fastest solve',
    howTo: [
      'Tap a cell, then tap a number to fill it in.',
      'Every row, column and 3×3 box needs the digits 1–9 exactly once.',
      'Use Notes to pencil in candidates while you work.',
    ],
    Component: lazy(() => import('./sudoku/Sudoku')),
  },
  {
    id: 'connect4',
    title: 'Connect Four',
    tagline: 'Four in a row beats the machine',
    category: 'Strategy',
    icon: 'discs',
    colors: ['#f43f5e', '#facc15'],
    scoring: 'high',
    scoreLabel: 'Wins',
    howTo: [
      'Tap a column to drop your disc into it.',
      'Line up four in a row — across, down or diagonally.',
      'The computer plays yellow, and it looks ahead.',
    ],
    Component: lazy(() => import('./connect4/ConnectFour')),
  },
  {
    id: 'breakout',
    title: 'Breakout',
    tagline: 'Bounce, smash, clear the wall',
    category: 'Arcade',
    icon: 'bricks',
    colors: ['#a3e635', '#14b8a6'],
    scoring: 'high',
    scoreLabel: 'Top score',
    howTo: [
      'Drag to slide the paddle, or steer with the arrow keys.',
      'Keep the ball alive and break every brick to clear the level.',
      'The ball speeds up as you go, and the angle depends where it lands.',
    ],
    Component: lazy(() => import('./breakout/BrickBreaker')),
  },
  {
    id: 'tictactoe',
    title: 'Tic-Tac-Toe',
    tagline: 'Simple rules, unbeatable opponent',
    category: 'Strategy',
    icon: 'noughts',
    colors: ['#ec4899', '#8b5cf6'],
    scoring: 'high',
    scoreLabel: 'Wins',
    howTo: [
      'Tap a square to place your X.',
      'Three in a row wins — across, down or diagonally.',
      'On Hard the computer plays perfectly, so a draw is a good result.',
    ],
    Component: lazy(() => import('./tictactoe/TicTacToe')),
  },
  {
    id: 'hangman',
    title: 'Hangman',
    tagline: 'Guess the word before the chances run out',
    category: 'Word',
    icon: 'gallows',
    colors: ['#f97316', '#e11d48'],
    scoring: 'high',
    scoreLabel: 'Longest streak',
    howTo: [
      'Pick letters to reveal where they sit in the hidden word.',
      'Every wrong letter costs one of your six chances.',
      'Solve the word to extend your streak.',
    ],
    Component: lazy(() => import('./hangman/Hangman')),
  },
  {
    id: 'anagram',
    title: 'Word Scramble',
    tagline: 'Unscramble as many words as you can',
    category: 'Word',
    icon: 'shuffle',
    colors: ['#8b5cf6', '#0ea5e9'],
    scoring: 'high',
    scoreLabel: 'Top score',
    howTo: [
      'Tap the jumbled letters to spell the hidden word.',
      'Longer words are worth more, and speed adds a bonus.',
      'Ninety seconds on the clock — skip anything you are stuck on.',
    ],
    Component: lazy(() => import('./anagram/AnagramRush')),
  },
  {
    id: 'doodle',
    title: 'Doodle Jump',
    tagline: 'Bounce ever upward, never look down',
    category: 'Arcade',
    icon: 'jump',
    colors: ['#22c55e', '#84cc16'],
    scoring: 'high',
    scoreLabel: 'Highest climb',
    howTo: [
      'You bounce automatically off every platform you land on.',
      'Tilt left and right by swiping, or use the arrow keys.',
      'Falling off the bottom of the screen ends the run.',
    ],
    Component: lazy(() => import('./doodle/SkyClimb')),
  },
  {
    id: 'pong',
    title: 'Pong',
    tagline: 'The original, still undefeated',
    category: 'Arcade',
    icon: 'paddle',
    colors: ['#e2e8f0', '#64748b'],
    scoring: 'high',
    scoreLabel: 'Best win margin',
    howTo: [
      'Drag your paddle up and down, or use the arrow keys.',
      'Send the ball past the computer to score.',
      'First to eleven takes the match.',
    ],
    Component: lazy(() => import('./pong/Pong')),
  },
  {
    id: 'lightsout',
    title: 'Lights Out',
    tagline: 'Every tap flips its neighbours too',
    category: 'Puzzle',
    icon: 'bulb',
    colors: ['#facc15', '#a16207'],
    scoring: 'low',
    scoreLabel: 'Fewest moves',
    howTo: [
      'Tapping a tile toggles it and the four tiles beside it.',
      'Switch every light off to solve the board.',
      'Each puzzle is generated to be solvable.',
    ],
    Component: lazy(() => import('./lightsout/LightsOut')),
  },
  {
    id: 'bubble',
    title: 'SameGame',
    tagline: 'Clear the board one cluster at a time',
    category: 'Puzzle',
    icon: 'bubbles',
    colors: ['#06b6d4', '#d946ef'],
    scoring: 'high',
    scoreLabel: 'Top score',
    howTo: [
      'Tap any group of two or more touching bubbles to pop them.',
      'Bigger clusters score far more than small ones.',
      'The board settles as bubbles fall — the game ends when no group is left.',
    ],
    Component: lazy(() => import('./bubble/BubblePop')),
  },
  {
    id: 'grouping',
    title: 'Connections',
    tagline: 'Sixteen words, four hidden groups',
    category: 'Word',
    icon: 'groups',
    colors: ['#6366f1', '#a855f7'],
    scoring: 'low',
    scoreLabel: 'Fewest mistakes',
    howTo: [
      'Sixteen words belong to four secret groups of four.',
      'Select four you think share a theme, then submit.',
      'Four wrong guesses and the puzzle is over — one away is a near miss.',
    ],
    Component: lazy(() => import('./grouping/CommonThread')),
  },
  {
    id: 'merge',
    title: 'Suika',
    tagline: 'Two of a kind merge into something bigger',
    category: 'Puzzle',
    icon: 'fruit',
    colors: ['#f43f5e', '#f59e0b'],
    scoring: 'high',
    scoreLabel: 'Top score',
    howTo: [
      'Tap a column to drop the fruit into the jar.',
      'Two matching fruits touch and merge into the next size up.',
      'The jar overflowing ends the run — keep the big ones low.',
    ],
    Component: lazy(() => import('./merge/FruitDrop')),
  },
  {
    id: 'triple',
    title: 'Triple Tile',
    tagline: 'Three of a kind clears the tray',
    category: 'Puzzle',
    icon: 'triple',
    colors: ['#14b8a6', '#8b5cf6'],
    scoring: 'high',
    scoreLabel: 'Top score',
    howTo: [
      'Tap a tile to move it into the tray at the bottom.',
      'Three matching tiles in the tray vanish together.',
      'Fill all seven tray slots without a match and you lose.',
    ],
    Component: lazy(() => import('./triple/TripleTile')),
  },
  {
    id: 'crossy',
    title: 'Crossy Road',
    tagline: 'Cross the traffic, one hop at a time',
    category: 'Arcade',
    icon: 'traffic',
    colors: ['#eab308', '#22c55e'],
    scoring: 'high',
    scoreLabel: 'Furthest hop',
    howTo: [
      'Swipe or use the arrow keys to hop one square at a time.',
      'Cars and trucks are fatal — watch the lane speeds.',
      'Every row forward scores; going back does not.',
    ],
    Component: lazy(() => import('./crossy/RoadHop')),
  },
  {
    id: 'flags',
    title: 'Flag Hunt',
    tagline: 'Name the country from its flag',
    category: 'Word',
    icon: 'globe',
    colors: ['#0ea5e9', '#22c55e'],
    scoring: 'high',
    scoreLabel: 'Best round',
    howTo: [
      'A flag appears — pick the country it belongs to.',
      'Answer quickly for a bigger time bonus.',
      'Ten flags per round, no second chances.',
    ],
    Component: lazy(() => import('./flags/FlagHunt')),
  },
  {
    id: 'shades',
    title: 'Odd Shade',
    tagline: 'Spot the tile that is subtly different',
    category: 'Reflex',
    icon: 'swatch',
    colors: ['#ec4899', '#f97316'],
    scoring: 'high',
    scoreLabel: 'Highest level',
    howTo: [
      'One tile in the grid is a slightly different shade.',
      'Tap it before the timer runs out.',
      'Each level adds tiles and narrows the difference.',
    ],
    Component: lazy(() => import('./shades/OddShade')),
  },
  {
    id: 'arrowescape',
    title: 'Arrow Escape',
    tagline: 'Clear the path and let every arrow break free',
    category: 'Puzzle',
    icon: 'arrow-escape',
    colors: ['#06b6d4', '#6366f1'],
    scoring: 'high',
    scoreLabel: 'Highest level',
    howTo: [
      'Tap any arrow pointing toward an open exit to release it.',
      'Blocked arrows will bump into obstacles and cost a life.',
      'Clear all arrows from the board to complete the level!',
    ],
    Component: lazy(() => import('./arrowescape/ArrowEscape')),
  },
  {
    id: 'chainreaction',
    title: 'Chain Reaction',
    tagline: 'Stack, trigger, and conquer the grid',
    category: 'Strategy',
    icon: 'atom',
    colors: ['#ff2a4b', '#00b0ff'],
    scoring: 'high',
    scoreLabel: 'Wins',
    howTo: [
      'Take turns placing orbs into empty cells or your own cells.',
      'Corners hold 1 orb and explode/split on the 2nd orb (2 neighbors).',
      'Edges hold 2 orbs and explode/split on the 3rd orb (3 neighbors).',
      'Center cells hold 3 orbs and explode/split on the 4th orb (4 neighbors).',
      'Exploding orbs capture adjacent cells and can trigger cascading chain reactions!',
      'Eliminate all opponent orbs from the grid to win.',
    ],
    Component: lazy(() => import('./chainreaction/ChainReaction')),
  },
]

export const byId = (id: string) => GAMES.find((g) => g.id === id)

export const CATEGORIES: GameCategory[] = [
  'Puzzle',
  'Arcade',
  'Reflex',
  'Strategy',
  'Memory',
  'Word',
]
