/**
 * Answer pool — common five-letter words, bundled so the game works fully
 * offline. Any word in this list is also accepted as a guess.
 */
export const ANSWERS: string[] = [
  'about','above','actor','acute','admit','adopt','adult','after','again','agent',
  'agree','ahead','alarm','album','alert','alike','alive','allow','alone','along',
  'alter','among','anger','angle','angry','ankle','apart','apple','apply','arena',
  'argue','armor','array','arrow','aside','asset','audio','audit','avoid','award',
  'aware','badly','baker','basic','beach','began','begin','being','below','bench',
  'birth','black','blade','blame','blank','blast','blend','blind','block','blood',
  'bloom','board','boost','booth','bound','brain','brand','brass','brave','bread',
  'break','breed','brick','bride','brief','bring','broad','broke','brown','brush',
  'build','built','bunch','burst','buyer','cabin','cable','camel','candy','carry',
  'carve','catch','cause','cease','chain','chair','chalk','chaos','charm','chart',
  'chase','cheap','check','cheer','chess','chest','chief','child','chill','choir',
  'chose','civic','civil','claim','class','clean','clear','clerk','click','cliff',
  'climb','clock','close','cloth','cloud','coach','coast','could','count','court',
  'cover','craft','crane','crash','crazy','cream','crime','crisp','cross','crowd',
  'crown','crude','cruel','crush','curve','cycle','daily','dairy','dance','dealt',
  'death','debut','decay','delay','dense','depth','derby','diary','digit','dirty',
  'ditch','dodge','doing','donor','doubt','dozen','draft','drain','drama','drank',
  'dream','dress','dried','drift','drill','drink','drive','drove','dying','eager',
  'eagle','early','earth','eight','elbow','elder','elect','elite','empty','ended',
  'enemy','enjoy','enter','entry','equal','error','event','every','exact','exist',
  'extra','faith','false','fancy','fatal','fault','favor','feast','fever','fiber',
  'field','fifth','fifty','fight','final','first','flame','flash','fleet','flesh',
  'float','flood','floor','flour','fluid','focus','force','forge','forth','forty',
  'forum','found','frame','fraud','fresh','front','frost','fruit','fully','funny',
  'ghost','giant','given','glass','glide','globe','glory','glove','grace','grade',
  'grain','grand','grant','grape','graph','grasp','grass','grave','great','green',
  'greet','grief','grill','grind','gross','group','grown','guard','guess','guest',
  'guide','guilt','habit','handy','happy','harsh','haste','hatch','haunt','heart',
  'heavy','hedge','hello','hence','hobby','honey','honor','horse','hotel','house',
  'human','humor','hurry','ideal','image','imply','index','inner','input','irony',
  'issue','ivory','jelly','jewel','joint','judge','juice','knife','knock','known',
  'label','labor','large','laser','later','laugh','layer','learn','lease','least',
  'leave','legal','lemon','level','lever','light','limit','linen','liver','lobby',
  'local','lodge','logic','loose','lover','lower','loyal','lucky','lunar','lunch',
  'lying','magic','major','maker','maple','march','marry','match','maybe','mayor',
  'meant','medal','media','melon','mercy','merge','merit','merry','metal','meter',
  'micro','might','minor','minus','mixed','model','moist','money','month','moral',
  'motor','mount','mouse','mouth','movie','music','naked','nasty','naval','nerve',
  'never','newly','night','noble','noise','north','notch','noted','novel','nurse',
  'ocean','offer','often','olive','onion','opera','orbit','order','organ','other',
  'ought','ounce','outer','owner','oxide','ozone','paint','panel','panic','paper',
  'party','pasta','patch','pause','peace','peach','pearl','pedal','penny','phase',
  'phone','photo','piano','piece','pilot','pinch','pitch','pivot','pixel','place',
  'plain','plane','plant','plate','plaza','point','polar','porch','pound','power',
  'press','price','pride','prime','print','prior','prize','probe','prone','proof',
  'proud','prove','pulse','punch','pupil','puppy','purse','queen','query','quest',
  'queue','quick','quiet','quilt','quite','quota','quote','radar','radio','raise',
  'rally','ranch','range','rapid','ratio','reach','ready','realm','rebel','refer',
  'reign','relax','relay','renew','repay','reply','rider','ridge','rifle','right',
  'rigid','rinse','ripen','risky','rival','river','roast','robot','rocky','roman',
  'rough','round','route','royal','rugby','ruler','rural','sadly','saint','salad',
  'sales','salon','sandy','sauce','scale','scare','scene','scope','score','scout',
  'screw','sense','serve','setup','seven','shade','shaft','shake','shall','shame',
  'shape','share','shark','sharp','shear','sheep','sheer','sheet','shelf','shell',
  'shift','shine','shiny','shirt','shock','shoot','shore','short','shown','sight',
  'silly','since','siren','sixth','skill','skirt','slate','sleep','slice','slide',
  'slope','small','smart','smell','smile','smoke','snake','sneak','solar','solid',
  'solve','sorry','sound','south','space','spare','spark','speak','speed','spell',
  'spend','spent','spice','spike','spill','spine','spite','split','spoke','spoon',
  'sport','spray','squad','stack','staff','stage','stain','stair','stake','stall',
  'stamp','stand','stare','start','state','steam','steel','steep','steer','stern',
  'stick','stiff','still','sting','stock','stone','stood','stool','store','storm',
  'story','stove','strap','straw','strip','stuck','study','stuff','style','suite',
  'sugar','sunny','super','surge','sweat','sweep','sweet','swift','swing','sword',
  'table','taken','tally','tango','taste','teach','tempo','tenth','thank','theft',
  'their','theme','there','these','thick','thigh','thing','think','third','those',
  'three','threw','throw','thumb','tiger','tight','timer','tired','title','toast',
  'today','token','tooth','topic','torch','total','touch','tough','towel','tower',
  'toxic','trace','track','trade','trail','train','trait','trash','treat','trend',
  'trial','tribe','trick','tried','troop','truck','truly','trunk','trust','truth',
  'tulip','tumor','twice','twist','ultra','uncle','under','union','unity','until',
  'upper','upset','urban','urged','usage','usual','utter','vague','valid','value',
  'valve','vapor','vault','venue','verse','video','vigor','villa','vinyl','viral',
  'virus','visit','vital','vivid','vocal','voice','voter','wagon','waist','waste',
  'watch','water','weary','wedge','weigh','weird','whale','wheat','wheel','where',
  'which','while','white','whole','whose','widen','wider','width','windy','wiser',
  'witch','woman','world','worry','worse','worst','worth','would','wound','wrist',
  'write','wrong','yield','young','youth','zebra',
]

const SET = new Set(ANSWERS)

export const isWord = (w: string) => SET.has(w.toLowerCase())

export const randomAnswer = () => ANSWERS[Math.floor(Math.random() * ANSWERS.length)]
